
export const TECHNICAL_WORDS = [
  "ALGORITHM", "DATABASE", "BACKEND", "FRONTEND", "FRAMEWORK", "FLUTTER", "REACT", "ANGULAR", "NODEJS", "EXPRESS",
  "MYSQL", "MONGODB", "SQLITE", "DOCKER", "GIT", "GITHUB", "REPOSITORY", "BRANCH", "COMMIT", "MERGE",
  "ANDROID", "PUSH", "FETCH", "DEPLOY", "HOSTING", "VSCODE", "COPILOT", "FIREBASE", "BLENDER", "AZURE",
  "ROUTING", "COMPONENT", "STATE", "PROPS", "HOOKS", "CONTEXT", "ASYNC", "AWAIT", "PROMISE", "CALLBACK",
  "THREAD", "PROCESS", "PACKAGE", "MODULE", "IMPORT", "EXPORT", "VARIABLE", "FUNCTION", "OBJECT", "ARRAY",
  "STRING", "INTEGER", "BOOLEAN", "SYNTAX", "COMPILER", "INTERPRETER", "DEBUGGER", "LOOPS", "CONDITION", "OPERATOR",
  "RECURSION", "ENCAPSULATION", "INHERITANCE", "POLYMORPHISM", "ABSTRACTION", "CLASS", "METHOD", "CONSTRUCTOR", "INSTANCE", "INTERFACE",
  "NETWORK", "PROTOCOL", "SOCKET", "CLIENT", "SERVER", "REQUEST", "RESPONSE", "ENDPOINT", "ROUTE", "SESSION",
  "TOKEN",  "JUPYTER", "SECURITY", "ENCRYPTION", "HASHING", "PERFORMANCE", "OPTIMIZATION", "DEBUGGING", "VERSIONING", "REFACTOR",
  "TERMINAL", "COMMAND", "SCRIPT", "PYCHARM", "BUILD", "REACTJS", "PYTHON", "JAVASCRIPT", "GEMINI", "CHATGPT"
];

export const LIGHT_COLORS = [
  '#ff1616', // rsed
  '#34ff34', // Green
  '#4da6ff', // Blue
  '#ffff2a', // Yellow
  '#ff3aff', // Purple
  '#36ffff', // Cyan
  '#ff8c1a', // Orange
];

export const WALL_LAYOUT = [
  ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
  ['I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q'],
  ['R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
];
