export const TECHNICAL_WORDS = [
  "ALGORITHM", "DATABASE", "BACKEND", "FRONTEND", "FRAMEWORK", "SYSTEM", "REACT", "ANGULAR", "NODEJS", "FUNCTIONAL",
  "OBJECTORIENTED", "MONGODB", "SQLITE", "DOCKER", "TYPESCRIPT", "GITHUB", "REPOSITORY", "BRANCH", "TESTING", "MERGE",
  "ANDROID", "PUSH", "FETCH", "DEPLOY", "HOSTING", "VSCODE", "COPILOT", "FIREBASE", "BLENDER", "AZURE",
  "ROUTING", "COMPONENT", "STATE", "PROPS", "VERCEL", "CONTEXT", "ASYNC", "AWAIT", "PROMISE", "CYBERSECURITY",
  "THREAD", "HOSTING", "PACKAGE", "MODULE", "IMPORT", "EXPORT", "VARIABLE", "FUNCTION", "OBJECT", "ARRAY",
  "STRING", "INTEGER", "BOOLEAN", "SYNTAX", "COMPILER", "INTERPRETER", "DATASCIENCE", "CONSTANTS", "CONDITION", "OPERATOR",
  "RECURSION", "ENCAPSULATION", "INHERITANCE", "POLYMORPHISM", "ABSTRACTION", "LOCALHOST", "METHOD", "CONSTRUCTOR", "INSTANCE", "INTERFACE",
  "NETWORK", "PROTOCOL", "SOCKET", "CLIENT", "SERVER", "REQUEST", "RESPONSE", "ENDPOINT", "ROUTE", "INTERNET",
  "TOKENIZATION", "JUPYTER", "SECURITY", "ENCRYPTION", "HASHING", "PERFORMANCE", "OPTIMIZATION", "OPERATING", "VERSIONING", "REFACTOR",
  "TERMINAL", "NETWORKING", "SCRIPTING", "PYCHARM", "BUILD", "REACTJS", "PYTHON", "JAVASCRIPT", "GEMINI", "CHATGPT"
];
